[package]
name = "ping_pong"
version = "0.1.0"
authors = ["alban"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
serenity = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
